version: 3

services:
  explorer:
    image: nekogawa/explorer
    restart: unless-stopped
    ports:
      - "8080:80"
    # Persist data for authentication
    environment:
      NODE_RPC: http://localhost:8545 # RPC endpoint of your node, you should make it accessible from both the container and the front end.